name = "plantai-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# Environment variables will be set in Cloudflare dashboard

[env.production.vars]
# Production environment variables

[[env.production.routes]]
pattern = "api.your-domain.com/*"
zone_name = "your-domain.com"
